
/* Drop Tables */

DROP TABLE CAREER CASCADE CONSTRAINTS;
DROP TABLE LICENSE CASCADE CONSTRAINTS;
DROP TABLE PROJECT_JOIN CASCADE CONSTRAINTS;
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE PROJECT CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE CAREER
(
	CAREER_NO number NOT NULL,
	MEMBER_NO number NOT NULL,
	CAREER_PERIOD_START date NOT NULL,
	CAREER_PERIOD_END date,
	CAREER_COMPANY varchar2(100) NOT NULL,
	CAREER_RANK varchar2(9) NOT NULL,
	CAREER_POSITION varchar2(100),
	PRIMARY KEY (CAREER_NO)
);


CREATE TABLE Employee
(
	MEMBER_NO number NOT NULL,
	MEMBER_NAME varchar2(28) NOT NULL,
	MEMBER_COMPANY varchar2(38),
	MEMBER_IDNUMBER varchar2(30) NOT NULL,
	MEMBER_ZIPCODE varchar2(10) NOT NULL,
	MEMBER_ADDRESS varchar2(200) NOT NULL,
	MEMBER_ADDRESS_DETAIL varchar2(100),
	MEMBER_RANK varchar2(50) NOT NULL,
	MEMBER_JOIN date NOT NULL,
	MEMBER_OUT date,
	MEMBER_ISNEW varchar2(20),
	MEMBER_HAVESKILL varchar2(1000),
	MEMBER_ISEXIT char,
	MEMBER_POSITION varchar2(100),
	PRIMARY KEY (MEMBER_NO)
);


CREATE TABLE LICENSE
(
	LICENSE_NO number NOT NULL,
	MEMBER_NO number NOT NULL,
	LICENSE_NAME varchar2(50) NOT NULL,
	LICENSE_LEVEL varchar2(10),
	LICENSE_GETDATE date,
	LICENSE_PUBLISHER varchar2(100),
	PRIMARY KEY (LICENSE_NO)
);


CREATE TABLE PROJECT
(
	PROJECT_NO number NOT NULL,
	PROJECT_NAME varchar2(1000) NOT NULL,
	PROJECT_CONTENT varchar2(1000),
	PROJECT_START date,
	PROJECT_END date,
	PROJECT_ORDER_COMPANY varchar2(200),
	PROJECT_CREATE_SKILL varchar2(500),
	PROJECT_ETC varchar2(1000),
	PROJECT_ISDELETE char,
	PRIMARY KEY (PROJECT_NO)
);


CREATE TABLE PROJECT_JOIN
(
	JOIN_NO number NOT NULL,
	MEMBER_NO number NOT NULL,
	PROJECT_NO number NOT NULL,
	JOIN_POSITION varchar2(500) NOT NULL,
	JOIN_IN date,
	JOIN_OUT date,
	PRIMARY KEY (JOIN_NO)
);



/* Create Foreign Keys */

ALTER TABLE CAREER
	ADD FOREIGN KEY (MEMBER_NO)
	REFERENCES Employee (MEMBER_NO)
;


ALTER TABLE LICENSE
	ADD FOREIGN KEY (MEMBER_NO)
	REFERENCES Employee (MEMBER_NO)
;


ALTER TABLE PROJECT_JOIN
	ADD FOREIGN KEY (MEMBER_NO)
	REFERENCES Employee (MEMBER_NO)
;


ALTER TABLE PROJECT_JOIN
	ADD FOREIGN KEY (PROJECT_NO)
	REFERENCES PROJECT (PROJECT_NO)
;



